### ISSUE TITLE
Incomplete code

### ISSUE THREAD

**Issue by edgeyboy** [vlang/doom#1]
The source code here only has one file :)

Did you forget to push them by any chance?

**Comment by medvednikov** [comment]
The rest will be pushed very soon.

**Comment by emilfihlman** [comment]
"Soon"

![image](https://user-images.githubusercontent.com/9070088/60197486-21952300-9848-11e9-84ce-0634bfb70a85.png)

**Comment by SoptikHa2** [comment]
When can we expect you to deliver the rest of the code, @medvednikov ? I'd like to test the 25x speedup of compilation :)

As you mentioned in readme, it builds in 0.7 seconds, so it's just `git push` away from publishing the transpiled version.

**Comment by betseg** [comment]
can't you read, it'll be pushed very soon

**Comment by nedpals** [comment]
Y'all asking when are the files be pushed but if you look at a different perspective, the language is in the middle of fast improvements especially in the compiler and as well as the C-to-V translator that is used to translate Doom in the process. 

Indeed, that some of the **WIPS** made the language became a meme in the programming community and bitching the features for some reason. But give him and the core team more time to finish a pretty solid language rather than putting the broken, error-filled transpiled files here for the sake of proving something.

**Comment by emilfihlman** [comment]
@nedpals that's a, pardon my language, but a bullshit excuse. Without providing anything of substance it's an empty statement and pretty mucj lying to the commonity for the sake of hype.

Just provide the thing you said and mark it as outdated if need be.

**Comment by medvednikov** [comment]
The feature was clearly marked as WIP before the release of the language, and there's a large part of the code translated and published, so saying nothing was provided is just ridiculous.
